"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Article = { id?: number; title: string; slug: string; excerpt: string; body: string; category: string; author: string; featuredImage: string | null; imageAlt: string | null; tags: string[]; metaTitle: string | null; metaDescription: string | null; status: string; featured: boolean };
const blank: Article = { title: "", slug: "", excerpt: "", body: "", category: "Insight", author: "", featuredImage: null, imageAlt: null, tags: [], metaTitle: null, metaDescription: null, status: "draft", featured: false };
export function ArticleEditor({ article = blank }: { article?: Article }) {
  const [data, setData] = useState({ ...article, tags: article.tags.join(", ") } as Omit<Article,"tags"> & {tags:string});
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [uploading, setUploading] = useState(false); const router = useRouter();
  function set(key: string, value: unknown) { setData(d => ({ ...d, [key]: value })); }
  async function upload(file?: File) { if (!file) return; setUploading(true); const fd = new FormData(); fd.append("file", file); const r = await fetch("/api/admin/upload", { method: "POST", body: fd }); const j = await r.json(); setUploading(false); if (r.ok) set("featuredImage", j.url); else setMessage(j.error); }
  async function save(status = data.status) { setSaving(true); setMessage(""); const url = article.id ? `/api/admin/articles/${article.id}` : "/api/admin/articles"; const r = await fetch(url, { method: article.id ? "PUT" : "POST", headers: { "Content-Type":"application/json" }, body: JSON.stringify({ ...data, status }) }); const j = await r.json(); setSaving(false); if (!r.ok) return setMessage(j.error || "Unable to save."); setMessage(status === "published" ? "Article published." : "Draft saved."); if (!article.id) router.replace(`/admin/articles/${j.id}`); router.refresh(); }
  async function remove() { if (!article.id || !confirm("Permanently delete this article? This cannot be undone.")) return; await fetch(`/api/admin/articles/${article.id}`, { method: "DELETE" }); router.replace("/admin/articles"); router.refresh(); }
  return <div className="grid xl:grid-cols-[1fr_320px] gap-6">
    <div className="space-y-6"><section className="bg-white border border-slate-200 rounded-lg p-6 space-y-5"><Field label="Article title"><input value={data.title} onChange={e=>{set("title",e.target.value); if(!article.id) set("slug",e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""));}} className="input text-lg font-medium" placeholder="A clear, specific headline" /></Field><Field label="URL slug" hint="Lowercase letters, numbers, and hyphens"><div className="flex items-center"><span className="text-xs bg-slate-100 border border-r-0 border-slate-300 rounded-l-md px-3 py-3 text-slate-500">/resources/</span><input value={data.slug} onChange={e=>set("slug",e.target.value)} className="input !rounded-l-none" /></div></Field><Field label="Excerpt" hint={`${data.excerpt.length}/180 recommended characters`}><textarea value={data.excerpt} onChange={e=>set("excerpt",e.target.value)} rows={3} className="input resize-y" placeholder="One concise paragraph used on listing pages and social previews." /></Field><Field label="Article body" hint="Use blank lines between paragraphs. Markdown headings (##) and lists (-) are supported by the public renderer."><textarea value={data.body} onChange={e=>set("body",e.target.value)} rows={22} className="input font-mono text-sm resize-y" placeholder={'## Section heading\n\nWrite the article here...'} /></Field></section>
    <section className="bg-white border border-slate-200 rounded-lg p-6"><h2 className="font-semibold text-slate-900">Search & sharing</h2><div className="mt-5 space-y-5"><Field label="Meta title" hint={`${(data.metaTitle||"").length}/60 characters`}><input value={data.metaTitle||""} onChange={e=>set("metaTitle",e.target.value)} className="input" /></Field><Field label="Meta description" hint={`${(data.metaDescription||"").length}/160 characters`}><textarea value={data.metaDescription||""} onChange={e=>set("metaDescription",e.target.value)} rows={3} className="input" /></Field></div></section></div>
    <aside className="space-y-5"><section className="bg-white border border-slate-200 rounded-lg p-5"><h2 className="text-sm font-semibold">Publishing</h2><div className="mt-4 grid gap-2"><button onClick={()=>save("published")} disabled={saving} className="rounded-md bg-[#18243a] text-white px-4 py-2.5 text-sm font-medium disabled:opacity-50">{saving ? "Saving…" : data.status === "published" ? "Update published article" : "Publish article"}</button><button onClick={()=>save("draft")} disabled={saving} className="rounded-md border border-slate-300 bg-white px-4 py-2.5 text-sm">Save as draft</button>{article.id && <a href={`/resources/${data.slug}`} target="_blank" className="rounded-md border border-slate-300 text-center px-4 py-2.5 text-sm">Open public page ↗</a>}{message && <p className="text-xs p-2 bg-slate-50 rounded text-slate-600">{message}</p>}</div></section>
    <section className="bg-white border border-slate-200 rounded-lg p-5 space-y-4"><Field label="Category"><select value={data.category} onChange={e=>set("category",e.target.value)} className="input"><option>Insight</option><option>News</option><option>Guide</option><option>Whitepaper</option></select></Field><Field label="Author"><input value={data.author} onChange={e=>set("author",e.target.value)} className="input" /></Field><Field label="Tags" hint="Comma separated"><input value={data.tags} onChange={e=>set("tags",e.target.value)} className="input" /></Field><label className="flex gap-2 items-center text-sm text-slate-700"><input type="checkbox" checked={data.featured} onChange={e=>set("featured",e.target.checked)} /> Feature on resources page</label></section>
    <section className="bg-white border border-slate-200 rounded-lg p-5"><Field label="Featured image" hint="JPG, PNG, or WebP. Maximum 5 MB."><input type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0])} className="text-xs w-full" /></Field>{uploading && <p className="mt-2 text-xs text-blue-700">Uploading…</p>}{data.featuredImage && <div className="mt-3"><img src={data.featuredImage} alt="Current featured" className="w-full aspect-video object-cover rounded border" /><button onClick={()=>set("featuredImage",null)} className="mt-2 text-xs text-red-700">Remove image</button></div>}<div className="mt-4"><Field label="Image alt text"><input value={data.imageAlt||""} onChange={e=>set("imageAlt",e.target.value)} className="input" /></Field></div></section>
    {article.id && <button onClick={remove} className="w-full rounded-md border border-red-200 bg-red-50 text-red-700 px-4 py-2.5 text-sm">Delete article</button>}</aside>
    <style jsx>{`.input{width:100%;border:1px solid #cbd5e1;border-radius:6px;background:white;padding:10px 12px;color:#0f172a;outline:none}.input:focus{border-color:#1d4ed8;box-shadow:0 0 0 3px #dbeafe}`}</style>
  </div>;
}
function Field({label,hint,children}:{label:string;hint?:string;children:React.ReactNode}) { return <label className="block"><span className="text-sm font-medium text-slate-700">{label}</span>{children}<span className="mt-1 block text-xs text-slate-400">{hint}</span></label>; }
